package com.openwatchproject.launcher;

public class ClockSkinConstants {
    public static final String CLOCK_SKIN_XML = "clock_skin.xml";
    public static final String CLOCK_SKIN_PREVIEW = "clock_skin_model.png";

    public static final int DIRECTION_CLOCKWISE = 1;
    public static final int DIRECTION_COUNTER_CLOCKWISE = 2;

    public static final int ROTATE_NONE = 0;
    public static final int ROTATE_HOUR = 1;
    public static final int ROTATE_MINUTE = 2;
    public static final int ROTATE_SECOND = 3;
    public static final int ROTATE_MONTH = 4;
    public static final int ROTATE_WEEK = 5;
    public static final int ROTATE_BATTERY = 6;
    public static final int ROTATE_DAY_NIGHT = 7; // Check this
    public static final int ROTATE_HOUR_SHADOW = 8;
    public static final int ROTATE_MINUTE_SHADOW = 9;
    public static final int ROTATE_SECOND_SHADOW = 10;
    public static final int ROTATE_BATTERY_CIRCLE = 11; // Check this
    public static final int ROTATE_DAY = 20; // Check this
    public static final int ROTATE_STEPS_TARGET = 101; // Check this

    public static final int ARRAY_YEAR_MONTH_DAY = 1;
    public static final int ARRAY_MONTH_DAY = 2;
    public static final int ARRAY_MONTH = 3;
    public static final int ARRAY_DAY = 4;
    public static final int ARRAY_WEEKDAY = 5;
    public static final int ARRAY_HOUR_MINUTE = 6;
    public static final int ARRAY_HOUR = 7;
    public static final int ARRAY_MINUTE = 8;
    public static final int ARRAY_SECOND = 9;
    public static final int ARRAY_WEATHER = 10;
    public static final int ARRAY_TEMPERATURE = 11;
    public static final int ARRAY_STEPS = 12;
    public static final int ARRAY_HEART_RATE = 13;
    public static final int ARRAY_BATTERY = 14;
    public static final int ARRAY_SPECIAL_SECOND = 15; // Check this
    public static final int ARRAY_YEAR = 16;
    public static final int ARRAY_BATTERY_CIRCLE = 17; // Check this
    public static final int ARRAY_STEPS_CIRCLE = 18; // Check this
    public static final int ARRAY_MOON_PHASE = 19;
    public static final int ARRAY_AM_PM = 20; // Check this
    public static final int ARRAY_FRAME_ANIMATION = 21; // Check this
    public static final int ARRAY_ROTATE_ANIMATION = 22; // Check this
    public static final int ARRAY_SNOW_ANIMATION = 23; // Check this
    public static final int ARRAY_BATTERY_CIRCLE_PIC = 24; // Check this
    public static final int ARRAY_PICTURE_HOUR = 30; // Check this
    public static final int ARRAY_PICTURE_MINUTER = 31; // Check this
    public static final int ARRAY_PICTURE_SECOND = 32; // Check this
    public static final int ARRAY_PICTURE_HOUR_DIGITE = 33; // Check this
    public static final int ARRAY_VALUE_WITH_PROGRESS = 34; // Check this
    public static final int ARRAY_VALUE_STRING = 35; // Check this
    public static final int ARRAY_VALUE_WITH_CLIP_PICTURE = 36; // Check this
    public static final int ARRAY_MONTH_NEW = 37; // Check this
    public static final int ARRAY_DAY_NEW = 38; // Check this
    public static final int ARRAY_SECOND_NEW = 39; // Check this
    public static final int ARRAY_STEPS_NEW = 40; // Check this
    public static final int ARRAY_KCAL_NEW = 41; // Check this
    public static final int ARRAY_STEPS_CIRCLE_NEW = 42; // Check this
    public static final int ARRAY_BATTERY_CIRCLE_NEW = 43; // Check this
    public static final int ARRAY_KCAL = 54;
    public static final int ARRAY_DISTANCE = 60;
    public static final int ARRAY_TEXT_PEDOMETER = 97;
    public static final int ARRAY_TEXT_HEARTRATE = 98;
    public static final int ARRAY_CHARGING = 99;
    public static final int ARRAY_TAP_ACTION = 100;
    public static final int ARRAY_YEAR_MONTH_DAY_2 = 101;
    public static final int ARRAY_DISTANCE_2 = 1001;
    public static final int ARRAY_DISTANCE_UNIT = 1002;
    public static final int ARRAY_TEMP_UNIT = 1011;

    public static final int MOVEMENT_SMOOTH = 0;
    public static final int MOVEMENT_QUARTZ = 1;
    public static final int MOVEMENT_OVERSHOOTING_QUARTZ = 2;
    public static final int MOVEMENT_ELASTIC = 3;
    public static final int MOVEMENT_DIGITAL_QUARTZ = 4;

    public static final int VALUE_TYPE_DRAWABLE = 0; // Check this
    public static final int VALUE_TYPE_STEP = 1; // Check this
    public static final int VALUE_TYPE_KCAL = 2; // Check this
    public static final int VALUE_TYPE_BATTERY = 3; // Check this
    public static final int VALUE_TYPE_SECOND = 4; // Check this
    public static final int VALUE_TYPE_MONTH_AND_DAY = 5; // Check this
    public static final int VALUE_TYPE_WEEKDAY = 6; // Check this

    public static final String TAG_ARRAY_TYPE = "arraytype";
    public static final String TAG_CENTERX = "centerX";
    public static final String TAG_CENTERY = "centerY";
    public static final String TAG_COLOR = "color";
    public static final String TAG_COLOR_ARRAY = "colorarray";
    public static final String TAG_DIRECTION = "direction";
    public static final String TAG_DRAWABLE = "drawable"; // Check this
    public static final String TAG_DRAWABLES = "drawables"; // Check this
    public static final String TAG_IMAGE = "image";
    public static final String TAG_MUL_ROTATE = "mulrotate";
    public static final String TAG_NAME = "name";
    public static final String TAG_OFFSET_ANGLE = "angle";
    public static final String TAG_ROTATE = "rotate";
    public static final String TAG_START_ANGLE = "startAngle"; // Check this
    public static final String TAG_TEXT_SIZE = "textsize"; // Check this
    public static final String TAG_DRAWABLE_FILE_TYPE = "xml"; // Check this
    public static final String TAG_DRAWABLE_TYPE = "png"; // Check this
    public static final String TAG_ANIMATION_ITEMS = "animationItems"; // Check this
    public static final String TAG_ANIMATION_ITEM = "animationItem"; // Check this
    public static final String TAG_DURATION = "duration"; // Check this
    public static final String TAG_COUNT = "count"; // Check this
    public static final String TAG_CHILD_FOLDER = "child_folder"; // Check this
    public static final String TAG_VALUE_TYPE = "value_type"; // Check this
    public static final String TAG_PROGRESS_DILIVER_ARC = "diliver_arc"; // Check this
    public static final String TAG_PROGRESS_DILIVER_COUNT = "diliver_count"; // Check this
    public static final String TAG_PROGRESS_RADIUS = "circle_radius"; // Check this
    public static final String TAG_PROGRESS_STROKEN = "circle_stroken"; // Check this
    public static final String TAG_PICTURE_SHADOW = "shadow_picture"; // Check this
    public static final String CURRENT_CLOCK_SKIN_KEY = "current_clock"; // Check this
    public static final String TAG_CLASS_NAME = "cls"; // Check this
    public static final String TAG_PACKAGE_NAME = "pkg"; // Check this
}
